--- SCRIPTS PARA OBTENER INFORMACIÓN DE PEDIDOS POR ALIAS DE USUARIO ----
USE ROE01;
GO;

--- FUNCION PARA OBTENER ESTADO DEL PEDIDO P O F ---
CREATE OR ALTER FUNCTION ESTADO_PEDIDO (@empresa VARCHAR(2), @numop CHAR(10))  
RETURNS CHAR(1)  
BEGIN  
 DECLARE @estped CHAR(1)  
 IF @empresa = '01'
 BEGIN
	 SELECT TOP 1 @estped = ESTADO  FROM ROE01.DBO.PED009  WHERE OPERACION= @numop;
 END
 ELSE
 BEGIN
     SELECT TOP 1 @estped = ESTADO  FROM ROE02.DBO.PED009  WHERE OPERACION= @numop;
 END;
 RETURN ISNULL(NULLIF(RTRIM(@estped), ''), 'P'); 
END;
GO;



--- DEVUELVE LISTA DE PEDIDOS POR USUARIO, SIN DETALLE DE PRODUCTOS ---
CREATE OR ALTER PROCEDURE USP_CONSULTA_PEDIDOS
    @ID_USUARIO VARCHAR(20)='',    
    @BUSQUEDA VARCHAR(100)='',    
    @NUM_PAGINA INT = 1,    
    @ALL_REG INT = 0,    
    @CANT_FILAS INT = 10,
	@DATE_START DATE = '2000-01-01',
	@DATE_END DATE = '9999-01-01',
	@ESTADO CHAR(1) = '%'
AS      
 /*== INICIO PAGINACIÓN ===*/    
 DECLARE     
  @INICIO VARCHAR(10),    
  @FIN VARCHAR(10),    
  -- @SQL NVARCHAR(MAX),    
  @IPAGINAS NUMERIC(10, 2),    
  @IMENOS1 INT,
  @EMPRESA VARCHAR(2)
    
  SET @IPAGINAS = CONVERT(NUMERIC(10, 2), @CANT_FILAS)    
  SET @IMENOS1 = @CANT_FILAS - 1    
    
  IF @ALL_REG = 0    
  BEGIN    
   SET @INICIO = ((@NUM_PAGINA * @CANT_FILAS) - @IMENOS1)    
   SET @FIN = (@NUM_PAGINA * @CANT_FILAS)    
  END    
  ELSE    
  BEGIN    
   SET @INICIO = 1    
   SET @FIN = 1000000    
  END    
 /*== FIN PAGINACIÓN ===*/   
 SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS LIKE @ID_USUARIO;
BEGIN
	IF @EMPRESA = '01'
	BEGIN
		WITH TBL_PEDIDOS    
		AS (    
		SELECT     
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,    
				ROW_NUMBER() OVER (ORDER BY P.OPERACION DESC) AS ITEM,    
				rTRIM(P.OPERACION) AS NUM_PED,    
				FORMAT(CONVERT(datetime, P.FECHA, 121), 'yyyy-MM-dd') AS FEC_PED,    
				rTRIM(P.RUC) AS RUC_CLI,    
				rTRIM(C.RAZON) AS DES_CLI,
				rTRIM(C.DIRECCION) AS DIR_CLI,    
				rTRIM(T.DESCRIPCION) AS MONEDA,
				rTRIM(T.SIMBOLO) AS ABR_MONEDA,    
				rTRIM(P.IDVENDEDOR) AS CDG_VEND,    
				P.BASE AS IMP_STOT,    
				P.IMPUESTO AS IMP_IGV,    
				P.TOTAL AS IMP_TTOT,    
				ROE01.DBO.ESTADO_PEDIDO(@EMPRESA, P.OPERACION) AS SWT_PED,
				P.ORDEN_COMPRA,
				P.FACTURA,
				P.OBSERVACIONES
		FROM ROE01.DBO.PED009 P JOIN ROE01.DBO.CUE001 C ON P.RUC = C.RUC AND C.IDVENDEDOR = P.IDVENDEDOR
	   JOIN [ROE00].DBO.GLO002 T    
		ON P.MONEDA = T.CODIGO WHERE rTRIM(P.USUARIO) = @ID_USUARIO    
		AND (
			STR(TRY_CONVERT(BIGINT, @BUSQUEDA)) LIKE LTRIM(STR(TRY_CONVERT(BIGINT, P.OPERACION))) OR
			rTRIM(P.OPERACION) LIKE '%' + @BUSQUEDA + '%'     
			OR rTRIM(P.RUC) LIKE '%' + @BUSQUEDA + '%'    
			OR rTRIM(C.RAZON) LIKE '%' + @BUSQUEDA + '%'
		) AND P.FECHA BETWEEN @DATE_START AND @DATE_END )
		SELECT *, ( SELECT CEILING(COUNT(*) / @IPAGINAS) FROM TBL_PEDIDOS ) AS TOTALPAGINAS    
		FROM TBL_PEDIDOS    
		WHERE ITEM >= @INICIO AND ITEM <= @FIN  AND (ISNULL(NULLIF(RTRIM(@ESTADO), ''), '') = '' OR  SWT_PED LIKE @ESTADO)
		ORDER BY FEC_PED DESC;
	END
	IF @EMPRESA = '02'
		BEGIN
		WITH TBL_PEDIDOS    
		AS (    
		SELECT     
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,    
				ROW_NUMBER() OVER (ORDER BY P.OPERACION DESC) AS ITEM,    
				rTRIM(P.OPERACION) AS NUM_PED,    
				FORMAT(CONVERT(datetime, P.FECHA, 121), 'yyyy-MM-dd') AS FEC_PED,    
				rTRIM(P.RUC) AS RUC_CLI,    
				rTRIM(C.RAZON) AS DES_CLI,
				rTRIM(C.DIRECCION) AS DIR_CLI,    
				rTRIM(T.DESCRIPCION) AS MONEDA,
				rTRIM(T.SIMBOLO) AS ABR_MONEDA,    
				rTRIM(P.IDVENDEDOR) AS CDG_VEND,    
				P.BASE AS IMP_STOT,    
				P.IMPUESTO AS IMP_IGV,    
				P.TOTAL AS IMP_TTOT,    
				ROE01.DBO.ESTADO_PEDIDO(@EMPRESA, P.OPERACION) AS SWT_PED,
				P.ORDEN_COMPRA,
				P.FACTURA,
				P.OBSERVACIONES
		FROM ROE02.DBO.PED009 P JOIN ROE02.DBO.CUE001 C ON P.RUC = C.RUC AND C.IDVENDEDOR = P.IDVENDEDOR
	    JOIN [ROE00].DBO.GLO002 T    
		ON P.MONEDA = T.CODIGO WHERE rTRIM(P.USUARIO) = @ID_USUARIO    
		AND (    
			STR(TRY_CONVERT(BIGINT, @BUSQUEDA)) LIKE LTRIM(STR(TRY_CONVERT(BIGINT, P.OPERACION))) OR
			rTRIM(P.RUC) LIKE '%' + @BUSQUEDA + '%'    
			OR rTRIM(C.RAZON) LIKE '%' + @BUSQUEDA + '%'
			OR LTRIM(STR(TRY_CONVERT(BIGINT, P.OPERACION))) LIKE STR(TRY_CONVERT(BIGINT, @BUSQUEDA))
		) AND P.FECHA BETWEEN @DATE_START AND @DATE_END )
		SELECT *, ( SELECT CEILING(COUNT(*) / @IPAGINAS) FROM TBL_PEDIDOS ) AS TOTALPAGINAS    
		FROM TBL_PEDIDOS    
		WHERE ITEM >= @INICIO AND ITEM <= @FIN  AND (ISNULL(NULLIF(RTRIM(@ESTADO), ''), '') = '' OR  SWT_PED LIKE @ESTADO)
		ORDER BY FEC_PED DESC;
	END
END;
GO;


EXEC USP_CONSULTA_PEDIDOS 'DESPACHO_IN', '', 1,0,10, '2024-11-01','2024-12-29','';
GO;

--- CONSULTA INFORMACION INDIVIDUAL DE CADA PEDIDO ---
CREATE OR ALTER PROCEDURE USP_CONSULTA_PEDIDO    
    @ID_USUARIO VARCHAR(20)='',    
    @OPERACION CHAR(7)
	AS
BEGIN
	DECLARE @EMPRESA VARCHAR(2);
	SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS LIKE @ID_USUARIO;
	IF @EMPRESA = '01'
		WITH TBL_PEDIDOS    
		AS (
		SELECT
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,    
				ROW_NUMBER() OVER (ORDER BY P.OPERACION DESC) AS ITEM,    
				rTRIM(P.OPERACION) AS NUM_PED,    
				FORMAT(CONVERT(datetime, P.FECHA, 121), 'yyyy-MM-dd') AS FEC_PED,
				P.HORA AS HORA_PED,
				P.CONDICION AS CONDICION_PED,
				CON.DESCRIPCION AS CONDICION_CLI,
				P.MONTO_LETRAS AS MONTO_LETRAS_PED,
				V.NOMBRE AS NOMBRE_VEND,
				rTRIM(P.RUC) AS RUC_CLI,    
				rTRIM(C.RAZON) AS DES_CLI,
				rTRIM(C.DIRECCION) AS DIR_CLI,
				rTRIM(P.DIRECCION) AS DIR_PED,
				rTRIM(C.TELEFONO_CONTACTO) AS TEL_CLI,
				rTRIM(C.TELEFONO) AS TEL_CLI_AUX,
				CONCAT(U.DEPARTAMENTO, ', ', U.PROVINCIA, ', ', U.DISTRITO) AS UBIGEO_CLI,
				rTRIM(T.DESCRIPCION) AS MONEDA,
				rTRIM(T.SIMBOLO) AS ABR_MONEDA,    
				rTRIM(P.IDVENDEDOR) AS CDG_VEND,    
				P.BASE AS IMP_STOT,    
				P.IMPUESTO AS IMP_IGV,    
				P.TOTAL AS IMP_TTOT,    
				ROE01.DBO.ESTADO_PEDIDO(@EMPRESA, P.OPERACION) AS SWT_PED,
				P.ORDEN_COMPRA,
				P.FACTURA,
				P.OBSERVACIONES
			FROM ROE01.DBO.PED009 P    
				JOIN ROE01.DBO.CUE001 C    
					ON P.RUC = C.RUC
				JOIN ROE00.dbo.SUP001 V
					ON @ID_USUARIO LIKE V.ALIAS
				LEFT JOIN ROE01.dbo.CUE017 CON
					ON  CON.CONDICION LIKE C.CONDICIONES
				LEFT JOIN ROE01.dbo.CUE005 U
					ON C.UBIGEO = U.UBIGEO
		JOIN ROE00.dbo.GLO002 T    
		ON P.MONEDA = T.CODIGO    
		WHERE rTRIM(P.USUARIO) = @ID_USUARIO AND P.OPERACION = @OPERACION) SELECT TOP(1) * FROM TBL_PEDIDOS;
	IF @EMPRESA = '02'
		WITH TBL_PEDIDOS    
		AS (    
		SELECT     
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,    
				ROW_NUMBER() OVER (ORDER BY P.OPERACION DESC) AS ITEM,    
				rTRIM(P.OPERACION) AS NUM_PED,    
				FORMAT(CONVERT(datetime, P.FECHA, 121), 'yyyy-MM-dd') AS FEC_PED,
				P.HORA AS HORA_PED,
				P.CONDICION AS CONDICION_PED,
				CON.DESCRIPCION AS CONDICION_CLI,
				P.MONTO_LETRAS AS MONTO_LETRAS_PED,
				V.NOMBRE AS NOMBRE_VEND,
				rTRIM(P.RUC) AS RUC_CLI,    
				rTRIM(C.RAZON) AS DES_CLI,
				rTRIM(C.DIRECCION) AS DIR_CLI,
				rTRIM(P.DIRECCION) AS DIR_PED,
				rTRIM(C.TELEFONO_CONTACTO) AS TEL_CLI,
				rTRIM(C.TELEFONO) AS TEL_CLI_AUX,
				CONCAT(U.DEPARTAMENTO, ', ', U.PROVINCIA, ', ', U.DISTRITO) AS UBIGEO_CLI,
				rTRIM(T.DESCRIPCION) AS MONEDA,
				rTRIM(T.SIMBOLO) AS ABR_MONEDA,    
				rTRIM(P.IDVENDEDOR) AS CDG_VEND,    
				P.BASE AS IMP_STOT,    
				P.IMPUESTO AS IMP_IGV,    
				P.TOTAL AS IMP_TTOT,    
				ROE01.DBO.ESTADO_PEDIDO(@EMPRESA, P.OPERACION) AS SWT_PED,
				P.ORDEN_COMPRA,
				P.FACTURA,
				P.OBSERVACIONES
			FROM ROE02.DBO.PED009 P    
				JOIN ROE02.DBO.CUE001 C    
					ON P.RUC = C.RUC
				JOIN ROE00.dbo.SUP001 V
					ON @ID_USUARIO LIKE V.ALIAS
				LEFT JOIN ROE02.dbo.CUE017 CON
									ON  CON.CONDICION LIKE C.CONDICIONES
				LEFT JOIN ROE02.dbo.CUE005 U
					ON C.UBIGEO = U.UBIGEO
				
		JOIN ROE00.dbo.GLO002 T    
		ON P.MONEDA = T.CODIGO
		WHERE rTRIM(P.USUARIO) = @ID_USUARIO AND P.OPERACION = @OPERACION) SELECT TOP(1) * FROM TBL_PEDIDOS; 
END;
GO;

EXEC USP_CONSULTA_PEDIDO 'DESPACHO_IN', '0000013';
GO;

--- CONSULTA LOS PRODUCTOS DE CADA PEDIDO POR INDIVIDUAL ---
CREATE OR ALTER PROCEDURE USP_CONSULTA_PRODUCTOS_PEDIDO    
    @USUARIO VARCHAR(20)='',    
    @OPERACION CHAR(7)
	AS
	DECLARE @IDVENDEDOR NUMERIC(5,0);
	DECLARE @VALIDO BIT
--SET @OPERACION = '0000004';
--SET @USUARIO = 'VENTA01';
	DECLARE @EMPRESA VARCHAR(2);
	SELECT @EMPRESA = EMPRESA_DEFECTO, @IDVENDEDOR = VENDEDOR FROM ROE00.DBO.SUP001 WHERE ALIAS LIKE @USUARIO;
	BEGIN
		IF @EMPRESA = '01'
		BEGIN
			SET @VALIDO = (SELECT 1 FROM ROE01.DBO.PED009 WHERE USUARIO = @USUARIO AND OPERACION = @OPERACION)
			SELECT P.IDPRODUCTO, PD.CODIGO_BARRA, CANTIDAD, P.PRECIO, P.IMPUESTO, P.MONTO, P.BASE, 'UND' AS TIPO, A.DESCRIPCION AS ALMACEN, A.IDALMACEN AS COD_ALMACEN, P.DESCRIPCION FROM ROE01.DBO.PED008 P
				JOIN ROE01.DBO.INV005 A ON A.IDALMACEN = P.IDALMACEN JOIN ROE01.dbo.INV001 PD ON PD.IDPRODUCTO = P.IDPRODUCTO
			WHERE OPERACION = @OPERACION AND @VALIDO = 1;
		END;
		IF @EMPRESA = '02'
		BEGIN
			SET @VALIDO = (SELECT 1 FROM ROE02.DBO.PED009 WHERE USUARIO = @USUARIO AND OPERACION = @OPERACION)
			SELECT P.IDPRODUCTO, PD.CODIGO_BARRA, CANTIDAD, P.PRECIO, P.IMPUESTO, P.MONTO, P.BASE, 'UND' AS TIPO, A.DESCRIPCION AS ALMACEN, A.IDALMACEN AS COD_ALMACEN, P.DESCRIPCION FROM ROE02.DBO.PED008 P
				JOIN ROE02.DBO.INV005 A ON A.IDALMACEN = P.IDALMACEN JOIN ROE02.dbo.INV001 PD ON PD.IDPRODUCTO = P.IDPRODUCTO
			WHERE OPERACION = @OPERACION AND @VALIDO = 1;
		END;
	END;
GO;

EXEC USP_CONSULTA_PRODUCTOS_PEDIDO 'DESPACHO_IN', '0000015'
		GO;

--- VERFICA SI LA CLASE DEL PRODUCTO ESTA INCLUIDO EN EL QUERY. Ej 3 en '3,4,5' ---


CREATE OR ALTER FUNCTION VERIFICAR_CLASE(@CLASE NUMERIC(5,0), @CLASES VARCHAR(20))
	RETURNS BIT
	BEGIN
	DECLARE @RESULT BIT
	IF @CLASE IN (SELECT CAST(value AS INT) AS ConvertedValue FROM STRING_SPLIT(@CLASES, ','))
		SET @RESULT = 1
	ELSE
		SET @RESULT = 0
	RETURN @RESULT
	END;
GO;

--- CONSULTA EL DETAALLE DE LOS PRODUCTOS FILTRADOS POR ALMACEN Y CLASE ---
CREATE OR ALTER PROCEDURE USP_STOCK_PRODUCTOS        
    @PRODUCTO VARCHAR(100)='',      
	@ID_ALMACEN NUMERIC(5,0),
	@CLASES VARCHAR(20),
	@RUC_CLIENTE VARCHAR(15),
	@USUARIO VARCHAR(20),
    @NUM_PAGINA INT = 1,      
    @ALL_REG INT = 0,      
    @CANT_FILAS INT = 10       
AS        
 /*== INICIO PAGINACIÓN ===*/      
 DECLARE       
  @INICIO VARCHAR(10),      
  @FIN VARCHAR(10),      
  -- @SQL NVARCHAR(MAX),      
  @IPAGINAS NUMERIC(10, 2),      
  @IMENOS1 INT,
  @IGV NUMERIC(6,2);
  SET @IPAGINAS = CONVERT(NUMERIC(10, 2), @CANT_FILAS)      
  SET @IMENOS1 = @CANT_FILAS - 1      
  DECLARE @EMPRESA VARCHAR(2);
  SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS LIKE @USUARIO;
  IF @ALL_REG = 0      
  BEGIN      
   SET @INICIO = ((@NUM_PAGINA * @CANT_FILAS) - @IMENOS1)      
   SET @FIN = (@NUM_PAGINA * @CANT_FILAS)      
  END      
  ELSE      
  BEGIN      
   SET @INICIO = 1      
   SET @FIN = 1000000      
  END      
 /*== FIN PAGINACIÓN ===*/      
BEGIN
	SELECT @IGV = IMPUESTO FROM ROE00.DBO.SUP003 WHERE EMPRESA = @EMPRESA;
	IF @EMPRESA = '01'
	BEGIN
		WITH TBL_STOCK      
		AS (
			SELECT    
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,      
				ROW_NUMBER() OVER (ORDER BY P.IDPRODUCTO ASC) AS ITEM,     
				P.IDPRODUCTO AS CDG_PROD,    
				RTRIM(P.DESCRIPCION) AS DES_PROD,    
				SUM(S.EXISTENCIA) AS STK_ACT,
				SUM(S.RESERVADO) AS STK_RES,
				RTRIM(A.IDALMACEN) AS ALMACEN,
				P.USA_IMPUESTO AS USA_IMPUESTO,
				@IGV AS IMPUESTO,
				PRECIO1,
	  			PRECIO2,
				PRECIO3,
				PRECIO4,
				PRECIO5
			FROM ROE01.DBO.INV001 P    
			JOIN ROE01.DBO.INV006 S ON P.IDPRODUCTO = S.IDPRODUCTO    
			JOIN ROE01.DBO.INV005 A ON S.IDALMACEN = A.IDALMACEN     
			AND P.ACTIVO = 1     
			WHERE     
			(ISNULL(@ID_ALMACEN, 0) = 0 OR A.IDALMACEN = @ID_ALMACEN) AND(    
			CONVERT(VARCHAR(100), P.IDPRODUCTO) LIKE '%'+@PRODUCTO+'%'--COD PRODUCTO    
			OR RTRIM(P.DESCRIPCION) LIKE '%'+@PRODUCTO+'%'--DESC PRODUCTO    
			) AND ROE01.DBO.VERIFICAR_CLASE(CLASE, @CLASES) = 1   
			GROUP BY     
			   P.IDPRODUCTO,    
			   P.DESCRIPCION,
			   P.USA_IMPUESTO,
			   S.EXISTENCIA,    
			   A.IDALMACEN,
			   P.PRECIO1,
			   P.PRECIO2,
			   P.PRECIO3,
			   P.PRECIO4,
			   P.PRECIO5
		) SELECT *,( SELECT CEILING(COUNT(*) / @IPAGINAS) FROM TBL_STOCK ) AS TOTALPAGINAS FROM TBL_STOCK WHERE ITEM >= @INICIO AND ITEM <= @FIN      
	END
	IF @EMPRESA = '02'
	BEGIN
		WITH TBL_STOCK      
		AS (
			SELECT    
				CONVERT(integer, COUNT(*) OVER (PARTITION BY 0)) TOTAL,      
				ROW_NUMBER() OVER (ORDER BY P.IDPRODUCTO ASC) AS ITEM,     
				P.IDPRODUCTO AS CDG_PROD,    
				RTRIM(P.DESCRIPCION) AS DES_PROD,    
				SUM(S.EXISTENCIA) AS STK_ACT,
				SUM(S.RESERVADO) AS STK_RES,
				RTRIM(A.IDALMACEN) AS ALMACEN,
				P.USA_IMPUESTO AS USA_IMPUESTO,
				@IGV AS IMPUESTO,
				PRECIO1,
	  			PRECIO2,
				PRECIO3,
				PRECIO4,
				PRECIO5
			FROM ROE02.DBO.INV001 P    
			JOIN ROE02.DBO.INV006 S ON P.IDPRODUCTO = S.IDPRODUCTO    
			JOIN ROE02.DBO.INV005 A ON S.IDALMACEN = A.IDALMACEN     
			AND P.ACTIVO = 1     
			WHERE     
			(ISNULL(@ID_ALMACEN, 0) = 0 OR A.IDALMACEN = @ID_ALMACEN) AND(    
			CONVERT(VARCHAR(100), P.IDPRODUCTO) LIKE '%'+@PRODUCTO+'%'--COD PRODUCTO    
			OR RTRIM(P.DESCRIPCION) LIKE '%'+@PRODUCTO+'%'--DESC PRODUCTO    
			) AND ROE01.DBO.VERIFICAR_CLASE(CLASE, @CLASES) = 1   
			GROUP BY     
			   P.IDPRODUCTO,    
			   P.DESCRIPCION,
			   P.USA_IMPUESTO,
			   S.EXISTENCIA,    
			   A.IDALMACEN,
			   P.PRECIO1,
			   P.PRECIO2,
			   P.PRECIO3,
			   P.PRECIO4,
			   P.PRECIO5
		) SELECT *,( SELECT CEILING(COUNT(*) / @IPAGINAS) FROM TBL_STOCK ) AS TOTALPAGINAS FROM TBL_STOCK WHERE ITEM >= @INICIO AND ITEM <= @FIN      
	END
END;
GO;


EXEC USP_STOCK_PRODUCTOS '',7,'3,25', '20600145330','DESPACHO_IN', 1,0,10
GO;

--- CONSULTA CLIENTES POR USUARIO (POR VENDEDOR) ---
CREATE OR ALTER PROCEDURE USP_SESION_CLIENTES     
 @USUARIO VARCHAR(20),
 @CRITERIO VARCHAR(100) = ''
AS      
BEGIN  
DECLARE @IDVENDEDOR NUMERIC(5,0), @EMPRESA VARCHAR(2);
SELECT @EMPRESA = EMPRESA_DEFECTO, @IDVENDEDOR = VENDEDOR FROM ROE00.dbo.SUP001 WHERE ALIAS = @USUARIO
	IF @EMPRESA = '01'
	BEGIN
		SELECT RUC, CONCAT(RUC, ' | ', RAZON) AS DESCRIPCION, IDVENDEDOR, PRECIO FROM ROE01.DBO.CUE001 WHERE IDVENDEDOR = @IDVENDEDOR AND ACTIVO = 1 AND CLASE LIKE 'C' AND (RAZON LIKE '%'+ @CRITERIO + '%' OR RUC LIKE '%'+ @CRITERIO + '%');
	END;
	IF @EMPRESA = '02'
	BEGIN
		SELECT RUC, CONCAT(RUC, ' | ', RAZON) AS DESCRIPCION, IDVENDEDOR, PRECIO FROM ROE02.DBO.CUE001 WHERE IDVENDEDOR = @IDVENDEDOR AND ACTIVO = 1 AND CLASE LIKE 'C' AND (RAZON LIKE '%'+ @CRITERIO + '%' OR RUC LIKE '%'+ @CRITERIO + '%');
	END;
END;
GO;

--- CONSULTA LISTA DE MONEDAS DISPONIBLES ---
CREATE OR ALTER PROCEDURE USP_SESION_MONEDAS
	AS SELECT CODIGO AS NUM_ITEM, DESCRIPCION AS DES_ITEM, SIMBOLO AS ABR_ITEM FROM ROE00.DBO.GLO002; 
GO;

--- CONSULTA TIPOS DE DOCUMENTO
CREATE OR ALTER PROCEDURE USP_SESION_DOCUMENTOS     
 @USUARIO VARCHAR(20)
AS      
BEGIN  
DECLARE @EMPRESA VARCHAR(2);
SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.dbo.SUP001 WHERE ALIAS = @USUARIO
	IF @EMPRESA = '01'
	BEGIN
		SELECT ROW_NUMBER() OVER (ORDER BY TIPO ASC) AS ID, TIPO, DESCRIPCION FROM ROE01.DBO.CUE008;
	END;
	IF @EMPRESA = '02'
	BEGIN
		SELECT ROW_NUMBER() OVER (ORDER BY TIPO ASC) AS ID, TIPO, DESCRIPCION FROM ROE02.DBO.CUE008;
	END;
END;
GO;

--- CREAR CLIENTES PARA VENDEDOR POR USUARIO
CREATE OR ALTER PROCEDURE USP_CREAR_CLIENTE(
	@USUARIO VARCHAR(20),
	@RAZON VARCHAR(150),
	@RUC VARCHAR(15),
	@DIRECCION VARCHAR(200),
	@TELEFONO VARCHAR(100),
	@CIUDAD VARCHAR(30),
	@CONTACTO VARCHAR(30),
	@TELEFONO_CONTACTO VARCHAR(20),
	@CORREO VARCHAR(50),
	@UBIGEO VARCHAR(10),
	@CONDICION VARCHAR(2),
	@TIPO_DOCUMENTO VARCHAR(2))
AS
BEGIN
	DECLARE @EMPRESA VARCHAR(2), @VENDEDOR NUMERIC(4,0);
	SELECT @EMPRESA = EMPRESA_DEFECTO, @VENDEDOR = VENDEDOR FROM ROE00.DBO.SUP001 WHERE ALIAS = @USUARIO;
	IF @EMPRESA = '01'
	BEGIN
	    IF EXISTS (SELECT 1 FROM ROE01.dbo.CUE001 WHERE RUC = @RUC AND CLASE LIKE 'C')
		BEGIN
            RAISERROR('El cliente yá se encuentra registrado.', 16, 1);
		END
		ELSE
		BEGIN
			INSERT INTO ROE01.dbo.CUE001(IDVENDEDOR, RAZON, RUC, DIRECCION, TELEFONO, CIUDAD, CONTACTO, TELEFONO_CONTACTO, CORREO, UBIGEO, CLASE, PRECIO, CONDICIONES, ACTIVO, CREADO_WEB, DOMICILIADO, TIPO_DOCUMENTO, FECHA)
				VALUES(@VENDEDOR, @RAZON, @RUC, @DIRECCION, @TELEFONO, @CIUDAD, @CONTACTO, @TELEFONO_CONTACTO, @CORREO, @UBIGEO, 'C', '1', @CONDICION, 1, 1, 1, @TIPO_DOCUMENTO, GETDATE());
		END
	END;
	IF @EMPRESA = '02'
	BEGIN
	    IF EXISTS (SELECT 1 FROM ROE02.dbo.CUE001 WHERE RUC = @RUC AND CLASE LIKE 'C')
		BEGIN
            RAISERROR('El cliente yá se encuentra registrado.', 16, 1);
		END
		ELSE
		BEGIN
			INSERT INTO ROE02.dbo.CUE001(IDVENDEDOR, RAZON, RUC, DIRECCION, TELEFONO, CIUDAD, CONTACTO, TELEFONO_CONTACTO, CORREO, UBIGEO, CLASE, PRECIO, CONDICIONES, ACTIVO, CREADO_WEB, DOMICILIADO, TIPO_DOCUMENTO, FECHA)
				VALUES(@VENDEDOR, @RAZON, @RUC, @DIRECCION, @TELEFONO, @CIUDAD, @CONTACTO, @TELEFONO_CONTACTO, @CORREO, @UBIGEO, 'C', '1', @CONDICION, 1, 1, 1, @TIPO_DOCUMENTO, GETDATE());
		END
	END;
END;
GO;

CREATE OR ALTER PROCEDURE USP_CONDICION(
	@USUARIO VARCHAR(20)
)
AS
BEGIN
	DECLARE @EMPRESA VARCHAR(2);
	SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS = @USUARIO;
	IF @EMPRESA = '01'
	BEGIN
		SELECT * FROM ROE01.dbo.CUE017;
	END;
	IF @EMPRESA = '02'
	BEGIN
		SELECT * FROM ROE02.dbo.CUE017;
	END;
END;
GO;

--- CONSULTA DE UBIGEOS
CREATE OR ALTER PROCEDURE USP_CONSULTA_UBIGEO(
	@USUARIO VARCHAR(20),
	@BUSQUEDA VARCHAR(100)
)
AS
BEGIN
	DECLARE @EMPRESA VARCHAR(2);
	SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS LIKE @USUARIO;
	IF @EMPRESA = '01'
	BEGIN
		SELECT TOP(500) UBIGEO, DISTRITO, PROVINCIA, DEPARTAMENTO FROM ROE01.dbo.CUE005 WHERE DISTRITO LIKE '%'+@BUSQUEDA+'%' OR
			PROVINCIA LIKE '%' + @BUSQUEDA + '%' OR DEPARTAMENTO LIKE '%' + @BUSQUEDA + '%' ORDER BY DEPARTAMENTO;
	END;
	IF @EMPRESA = '02'
	BEGIN
		SELECT TOP(500) UBIGEO, DISTRITO, PROVINCIA, DEPARTAMENTO FROM ROE02.dbo.CUE005 WHERE DISTRITO LIKE '%'+@BUSQUEDA+'%' OR
			PROVINCIA LIKE '%' + @BUSQUEDA + '%' OR DEPARTAMENTO LIKE '%' + @BUSQUEDA + '%' ORDER BY DEPARTAMENTO;
	END;
END;
GO;

--- CAMBIAR A BASE DE DATOS PARA SESION DE USUARIO

USE ROE00
SELECT *, CONVERT(VARCHAR(20), CLAVE) FROM SUP001
GO;

CREATE OR ALTER PROCEDURE USP_USUARIO 
 @USER VARCHAR(20)      
AS      
BEGIN      
 SELECT IDREGISTRO, VENDEDOR, NOMBRE, EMPRESAS, EMPRESA_DEFECTO, PUEDE_CAMBIAR_PRECIO_FACTURACION, OPERACIONES_ESPECIALES, PRECIO_PERMITIDOS FROM ROE00.DBO.SUP001 WHERE ALIAS=@USER;
END
GO;

CREATE OR ALTER PROCEDURE USP_EMPRESA(
	@USUARIO VARCHAR(20)
)
AS
BEGIN
	DECLARE @EMPRESA VARCHAR(2);
	SELECT @EMPRESA = EMPRESA_DEFECTO FROM ROE00.DBO.SUP001 WHERE ALIAS = @USUARIO;
	SELECT E.EMPRESA, E.RUC, E.CODIGO, ED.PRECIO_TIENE_IMPUESTO, ED.NOMBRE_PRECIO1, ED.NOMBRE_PRECIO2, ED.NOMBRE_PRECIO3, ED.NOMBRE_PRECIO4, ED.NOMBRE_PRECIO5 FROM ROE00.dbo.SUP002 E JOIN ROE00.dbo.SUP003 ED ON E.CODIGO = ED.EMPRESA WHERE E.CODIGO = @EMPRESA;
END;
GO;


--- CONSULTA PARA INICIAR SESION, DEVUEKVE ESTADO E INFORMACION DEL USUARIO ---

CREATE OR ALTER PROCEDURE USP_SESION_USUARIO       
 @USER VARCHAR(20),      
 @PASSWORD VARCHAR(20)      
AS      
BEGIN      
 DECLARE @RESPONSE INT;      
 DECLARE @PASS_ENCRY VARCHAR(20);      
 DECLARE @PASS_DESNCRY VARCHAR(20);
 DECLARE @COD_VENDEDOR NUMERIC(4,0);
 DECLARE @IDREGISTRO NUMERIC(10, 0);
 DECLARE @EMPRESAS VARCHAR(200);
 DECLARE @EMPRESA CHAR(2);
 SET @PASS_ENCRY = (SELECT CLAVE FROM SUP001 WHERE ALIAS=@USER);    
 SET @PASS_DESNCRY= CONVERT(VARCHAR(20), @PASS_ENCRY);
      
 print @PASS_ENCRY      
 print @PASS_DESNCRY      
      
 IF EXISTS(SELECT 1 FROM SUP001 WHERE ALIAS=@USER AND @PASS_DESNCRY = @PASSWORD AND BLOQUEADO=0 AND GETDATE() < VENCE)      
  BEGIN
   SELECT @COD_VENDEDOR = VENDEDOR, @IDREGISTRO = IDREGISTRO, @EMPRESAS = EMPRESAS, @EMPRESA = EMPRESA_DEFECTO FROM SUP001 WHERE ALIAS=@USER;	
   SET @RESPONSE = 1;--SUCCESS      
  END      
 ELSE      
  BEGIN      
   SET @RESPONSE = 0;--ERROR 
   SET @COD_VENDEDOR = -1;
   SET @EMPRESAS = '';
   SET @EMPRESA = '';
  END      
        
 SELECT @RESPONSE AS RESPONSE, @IDREGISTRO AS ID, @COD_VENDEDOR AS VENDEDOR, @EMPRESAS AS EMPRESAS, @EMPRESA AS EMPRESA   
END

EXEC USP_SESION_USUARIO 'HANS', '1234'
GO;

-- OBTENER LAS EMPRESAS DEL USUARIO
CREATE OR ALTER PROCEDURE ST_OBTENER_EMPRESAS_USUARIO
    @USUARIO VARCHAR(20)
AS
BEGIN
    SELECT e.CODIGO, e.EMPRESA, ed.PRECIO_TIENE_IMPUESTO
    FROM SUP001 u
    CROSS APPLY STRING_SPLIT(u.EMPRESAS, ';') AS splitEmpresas
    INNER JOIN SUP002 e ON e.codigo = splitEmpresas.value
	INNER JOIN SUP003 ed ON ed.EMPRESA = e.CODIGO
    WHERE u.ALIAS = @USUARIO;
END;
GO;

-- CAMBIAR LAS EMPRESAS DEL USUARIO
CREATE OR ALTER PROCEDURE ST_CAMBIAR_EMPRESA(
	@USUARIO VARCHAR(20),
	@EMPRESA VARCHAR(3))
AS
BEGIN
	DECLARE @EXISTS BIT;
	SELECT @EXISTS = 1 FROM SUP001 CROSS APPLY STRING_SPLIT(EMPRESAS, ';') AS splitEmpresas
	WHERE @EMPRESA = splitEmpresas.value AND ALIAS = @USUARIO;

	IF @EXISTS = 1
	BEGIN
		UPDATE SUP001
		SET EMPRESA_DEFECTO = @EMPRESA
		WHERE ALIAS = @USUARIO;

	END;
END;
GO;