USE [ROE01]
GO

/****** Object:  StoredProcedure [dbo].[SP_HISTORICO_ORDEN_PEDIDO_POR_ZONA]    Script Date: 30/12/2025 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_HISTORICO_ORDEN_PEDIDO_POR_ZONA]
    @FECHAINICIO DATETIME = NULL,
    @FECHAFIN DATETIME = NULL,
    @IDVENDEDOR INT = NULL,
    @CONDESPACHO BIT = NULL
AS
BEGIN
    SELECT 
        VEN.NOMBRE AS VENDEDOR,
        PED009.OPERACION, 
        PED009.FECHA, 
        LEFT(PED009.NOMBRE, 30) AS CLIENTE,
        PED009.REFERENCIA,
        PED009.TOTAL / NULLIF(PED009.TASA_DOLAR, 0) AS TOTAL,
        MON.SIMBOLO,
        REPLACE(PED009.GUIA,'20600145330-09-','') AS GUIA,
        (SELECT TOP 1 REFERENCIA FROM INV009 WHERE PEDIDO = PED009.OPERACION) AS FACTURA,
        CASE 
            WHEN PED009.ESTADO = '' THEN 'PENDIENTE' 
            WHEN PED009.ESTADO = 'A' THEN 'ANULADO' 
            WHEN PED009.ESTADO = 'D' THEN 'DESPACHADO' 
            WHEN PED009.ESTADO = 'P' THEN 'PARCIAL' 
        END AS ESTADO,
        PED009.ACEPTADA_POR_LA_SUNAT,
        CAST(CASE WHEN PED009.REFERENCIA_ANULADA <> '' THEN 1 ELSE 0 END AS BIT) AS ANU,
        (SELECT SUM(CANTIDAD) FROM PED008 WHERE PED008.OPERACION = PED009.OPERACION) AS ORGINAL,
        (SELECT SUM(CANTIDAD_DESPACHADA) FROM PED008 WHERE PED008.OPERACION = PED009.OPERACION) AS DESPACHADA,
        -- Campos adicionales para zona (al final)
        CONCAT(CUE005.DISTRITO, ', ', CUE005.PROVINCIA, ', ', CUE005.DEPARTAMENTO) AS UBIGEO,
        CUE010.CORTO AS ZONA
    FROM PED009
    INNER JOIN ROE00.dbo.GLO002 MON ON PED009.MONEDA = MON.CODIGO
    INNER JOIN CUE004 VEN ON PED009.IDVENDEDOR = VEN.IDVENDEDOR
    -- JOIN con tabla de clientes para obtener Ubigeo
    LEFT JOIN CUE001 ON PED009.RUC = CUE001.RUC
    -- JOIN con tabla de ubigeos para obtener Departamento, Provincia, Distrito
    LEFT JOIN CUE005 ON CUE001.UBIGEO = CUE005.UBIGEO
    -- JOIN con tabla de zonas (CUE010 se relaciona con CUE005 por UBIGEO, pero CUE010 puede tener otro nombre de campo)
    -- Si CUE010 tiene un campo diferente, ajustar aquí. Posibles opciones:
    -- LEFT JOIN CUE010 ON CUE005.UBIGEO = CUE010.UBIGEO_CODIGO
    -- O si CUE010 tiene ZONA como código que se relaciona:
    LEFT JOIN CUE010 ON CUE005.ZONA = CUE010.ZONA
    WHERE 
        PED009.IDDOCUMENTO = 13
        AND (@FECHAINICIO IS NULL OR PED009.FECHA >= @FECHAINICIO)
        AND (@FECHAFIN IS NULL OR PED009.FECHA <= @FECHAFIN)
        AND (@IDVENDEDOR IS NULL OR PED009.IDVENDEDOR = @IDVENDEDOR)
        AND (@CONDESPACHO IS NULL OR 
             (@CONDESPACHO = 1 AND (SELECT SUM(CANTIDAD_DESPACHADA) FROM PED008 WHERE PED008.OPERACION = PED009.OPERACION) > 0) OR
             (@CONDESPACHO = 0 AND (SELECT SUM(CANTIDAD_DESPACHADA) FROM PED008 WHERE PED008.OPERACION = PED009.OPERACION) = 0))
    ORDER BY CONCAT(CUE005.DISTRITO, ', ', CUE005.PROVINCIA, ', ', CUE005.DEPARTAMENTO), PED009.OPERACION DESC;
END
GO

